//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildCars.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int CarID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string CarYear { get; set; }
        public string BodyStyle { get; set; }
        public string Trans { get; set; }
        public string Color { get; set; }
        public string Interior { get; set; }
        public string Mileage { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public string CarDescription { get; set; }
        public string CarType { get; set; }
        public string Vin { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsPurchased { get; set; }
        public Nullable<int> MakeID { get; set; }
        public string PicturePath { get; set; }
    
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual Make Make { get; set; }
    }
}
