//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildCars.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleID { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<System.DateTime> DateOfSale { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string StreetOne { get; set; }
        public string StreetTwo { get; set; }
        public string City { get; set; }
        public string SaleState { get; set; }
        public string Zip { get; set; }
        public string PurchaseType { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
